### ISSUE TITLE
Font not showing properly when using in mpdf.

### ISSUE THREAD

**Issue by Uhtredtb** [cadsondemak/kanit#10]
I’m having an issue using Kanit font when used in MPDF https://www.npmjs.com/package/mdpdf

When the PDF generated some of the Kanit letter is not showing as properly as it should be. Please see the screenshot attached. 

![5D7A50F1-798F-46FD-A7AE-F10489951A08](https://user-images.githubusercontent.com/25810154/70602543-467b2800-1c27-11ea-975e-a941bf7f1eca.jpeg)

Here is how it should be 
![D60F2ABE-DEDB-4687-B47B-6267B78ADD0B](https://user-images.githubusercontent.com/25810154/70602564-4da23600-1c27-11ea-8fb5-4dbea20b79e0.jpeg)

I couldn’t find anything on google or else where, this is my last resort please kindly help and check this out for me. 

Thank you so much. 
Regards,
T

**Comment by trungkmy** [comment]
i'm facing the same issue with Kanit font, Angsana New font and other PDF Export tool (Kendo PDF). After spend much time to research, my solution is just changed the font to **Arial Unicode MS** 🤣

**Comment by davelab6** [comment]
Sadly this looks like a bug in mpdf to me, as the font works in regular Chromium
