### ISSUE TITLE
GF update : vertical metrics

### ISSUE THREAD

**Issue by RosaWagner** [cadsondemak/kanit#12]
I am almost done with reviewing the changes to update the font on Google Fonts, although few things doesn't match Google specs anymore. Biggest issue is the vertical metrics, I think a decision should be made before I submit to you a PR with the modifications.

**Version 1.051 (Source repo)**
typoAscender = 750;
typoDescender = "-250";
typoLineGap = 200;
winAscent = 1100;
winDescent = 395;
use_typo_metrics = disabled

**Version 1.002 (GF repo)**
typoAscender = 750;
typoDescender = "-250";
typoLineGap = 200;
winAscent = 1100;
winDescent = 395;
hheaAscender = 1100;
hheaDescender = "-395";
use_typo_metrics = disabled

**What’s wrong with it ?**
- Source version misses HHEA metrics to give instructions to applications in Mac environment
- Both versions have USE_TYPO_METRICS disabled, which mean that Windows applications are using the WIN metrics to calculate linespacing.
- TYPO and WIN metrics are not equivalent, which means that softwares which use TYPO metrics over WIN metrics (when Use_Typo_metrics is disabled) don’t display linespacing the same way within the same OS environment.
- LineGap is not 0. This metric is not consistently used by softwares, ie some softwares within the same OS environment may display it and other not.
- WIN metrics don’t cover the highest glyph of the font, it may be cut off when rendered on Windows text machines. (Highest: nikhahit_maiTri-thai (top y: 1174.0), Lowest: saraUu-thai.small (bottom y: -391.0))

**What is recommended ?**
- Since Windows softwares support ‘use_typo_metrics’ since 2006, it is recommended to enable this option so WIN metrics are used only to set the size of the rendering box, TYPO metrics for the linespacing. 
- It is good practice to round up Y-Max and Y-Min for WIN metrics to make sure glyphs are entirely displayed even at small ppm sizes.
- To optimise cross-platforms consistency, it is then recommended to synchronise HHEA and TYPO metrics, and set LineGap values to 0.
- Ascenders metrics should cover an accentuated capital to allow primitive text editors to display accents in first line of texts (highest single accentuated caps is A with hook above y=935)
- For optimal user experience it is also recommended to centred capitals in the text-frame (caps-height=644) and provide an average baseline to baseline distance of 120%-130% of the font size. But doing so, in this case, will greatly modify layout of existing documents.

**Suggested vertical metrics for next update (version 2.000)**
_1) We give former WIN metrics to TYPO and HHEA metrics for a minimal impact on web and office applications (but existing indesign documents will be impacted, and linespacing is a bit loose)._
TypoAscender = HheaAscender = 1100
TypoDescender = HheaDescender = -395
TypoLineGap = HheaLineGap = 0
winAscent = 1180 (y-max rounded up)
winDescent = 400 (y-min rounded up)
use_typo_metrics = enabled

_2) Another solution for good user experience would be these values (linespacing 125% of UPM, caps centred), although it would modify deeply existing documents on every platforms and applications:_
TypoAscender = HheaAscender = 946
TypoDescender = HheaDescender = -302
TypoLineGap = HheaLineGap = 0
winAscent = 1180
winDescent = 400
use_typo_metrics = enabled

@davelab6 :  I used Marc script to have about 125% of linespacing and I then recalculated to center capitals (GF script suggest 975 and -242). Which solution would you recommend ?

**Comment by RosaWagner** [comment]
Maybe there were a lot of informations in this post. Let's rephrase this way: vertical metrics doesn't match Google Spec, the update of this font is a good opportunity to correct the vertical metrics as well :) To avoid regression we suggest solution 1) above. The important thing here is to preserve current paragraph set up on web pages using the font. Do you agree ?

**Comment by suppakit-** [comment]
I think it is good if it adapts to Google Spec. What we care about is people who have used previous versions. If there is no effect on the original layout.

**Comment by RosaWagner** [comment]
On the web pages there will be no changes.

**Comment by suppakit-** [comment]
OK. I agree with you. Thank you very much for the advice.
