### ISSUE TITLE
Kerning

### ISSUE THREAD

**Issue by RosaWagner** [cadsondemak/kanit#14]
I noticed unusual kerning pairs. Shall I review it too, or do you prefer to let it like this ?

![Capture d’écran 2020-06-03 à 16 14 06](https://user-images.githubusercontent.com/12222436/83647784-9377ff80-a5b5-11ea-8c51-3626b49c5e50.png)

**Comment by suppakit-** [comment]
Please review and adjust as appropriate. Thank you.
