### ISSUE TITLE
Wrong Nighahit (U+0E4D) & Tones order on Mac OS & Safari

### ISSUE THREAD

**Issue by sungsit** [cadsondemak/kanit#2]
When input Consonants+Tone+SaraAm (U+0E33) sequence the font should display as Consonants+Nighahit+Tone+SaraAA (U+0E32). That means you need to swap Nighahit & Tones positions.

![screen shot 2558-11-09 at 8 03 49 pm](https://cloud.githubusercontent.com/assets/3959487/11034603/6a05f148-871f-11e5-90fc-6f7abec5a103.png)

I believe this is CoreText’s bug only because it can’t handle contextual chaining feature well but as installable fonts, it is critical for Thai eyes and need to be fixed.

Other families also have the same problem.

**Comment by davelab6** [comment]
@sungsit do you know of any font that have fixed this?

**Comment by davelab6** [comment]
@sungsit can you confirm that this occurs in web browsers?

**Comment by sungsit** [comment]
Yes, I can confirm. It's CoreText's bug, even Tahoma have this problem on Mac OS & Safari. I've discussed with @suppakit- here http://www.f0nt.com/forum/index.php/topic,22875.0.html

**Comment by sungsit** [comment]
TLWG fonts have no problem with this http://linux.thai.net/projects/fonts-tlwg. I'm trying to patch Kanit GSUB features with TLWG method. I'll push to my fork when ready.

**Comment by sungsit** [comment]
To be clear, Chrome, FireFox & Opera have no problem with this on Mac because of HarfBuzz.
